name: quranirab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  xml2json: ^5.3.1
  quran: ^1.0.4
  xml_parser: ^1.0.0
  xml: ^5.3.1
  flutter_parse: ^1.0.1
  postgres: ^2.4.1+2
  flutter_js: ^0.5.0+3
  js: ^0.6.0
  webview_flutter: ^2.3.0
  google_sign_in: ^5.2.1
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  easy_rich_text: ^1.0.1
  nb_utils:
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.0
  top_snackbar_flutter: 1.0.0
  flutter_search_bar: ^2.1.0
  cool_dropdown: ^1.4.1
  flutter_svg:
  cached_network_image:
  material_design_icons_flutter: ^5.0.5955-rc.1
  arabic_numbers: ^1.0.0
  custom_pop_up_menu:
  async: ^2.8.1
  responsive: ^0.3.11+11
  popover: ^0.2.6+3
  skeleton_loader: ^2.0.0+4
  firebase_storage: ^10.2.13
  dio: ^4.0.6
  get_storage: ^2.0.3
  dropdown_search:
  tree_view: ^0.0.6
  floating_action_bubble: ^1.1.4
  group_radio_button: ^1.2.0
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  auto_size_text: ^3.0.0
  universal_html:
  loading_animation_widget: ^1.2.0+1
  flutter_stripe: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true # Add this line

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/break.json
    - assets/surah_split.json
    - assets/Image3.png
    - assets/Image1.png
    - assets/Image2.png
    - assets/Image7.png
    - assets/data/words.json
    - assets/data/alfatihah_words.json
    - assets/data/quran_text.json
    - assets/data/quran_text_all.json
    - assets/data/tajweed_waw_android.txt
    - assets/javascript/qw-slicer.js
    - assets/quranirab_logo2_white.png
    - assets/quranirab.png
    - assets/sura_header.png
    - assets/javascript/index.html
    - assets/unicode_line_break.txt
    - assets/images/dark.jpg
    - assets/images/light.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MeQuran2
      fonts:
        - asset: fonts/me_quran2.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
